# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13171ed8a47c0cda1b85b82a0adcd54132a6cc943959c36858825a03039a230c2bfcd5e0565cfece9c5f7dbfcba717b30c6d8c8760edc1534cac07781d931835

test:
  secret_key_base: a1487bd741af3156e43b8253db45b51b3a1876d605356e4d6bc5cc4bddd18d04e744e5e5300662c6307d07fe239ee2492cfd7fbbd01e5d9179f7ed055095091d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
